extends Node
## Core reading engine. Manages word selection, validation, difficulty progression,
## and spaced repetition for educational effectiveness.

signal target_word_changed(word: String, hint_image: String)
signal letter_collected(letter: String, position: int)
signal word_spelled_correctly(word: String)
signal wrong_letter_rejected(letter: String)
signal letter_lost()  # Emitted when a collected letter is lost (wrong pick penalty)

const WORDS_PATH := "res://data/words.json"
const WORD_BANK_TRES := "res://data/words/word_bank.tres"

var word_bank: Array[Dictionary] = []
var _resource_bank: Resource = null  # WordBank resource (if loaded)
var current_target_word := ""
var current_hint_image := ""
var collected_letters: Array[String] = []
var current_difficulty := 1
var _word_attempts: Dictionary = {}  # word -> {correct: int, hints_used: int, time_ms: int}
var _recent_words: Array[String] = []  # Last N words to avoid repetition
const RECENT_WORD_MEMORY := 30  # How many recent words to avoid repeating

# Fixed starter sequence — these words always come first in order
# Phonics-informed: CVC words the child already knows, pets early for engagement
var _starter_sequence: Array[String] = ["cat", "dog", "sun", "hut"]
var _starter_index := 0
var _starter_complete := false

func _ready() -> void:
	_load_word_bank()
	# Restore starter sequence progress from saved state
	_starter_index = GameManager.starter_index
	_starter_complete = GameManager.starter_complete
	GameManager.progress_reset.connect(_on_progress_reset)

func _load_word_bank() -> void:
	# Source of truth: data/words.json. The .tres is a cached/typed mirror,
	# regenerated by tools/import_words.gd. To avoid a stale .tres masking
	# fresh JSON edits, we compare mtimes and prefer whichever is newer.
	var json_exists := FileAccess.file_exists(WORDS_PATH)
	var tres_exists := ResourceLoader.exists(WORD_BANK_TRES)
	var prefer_tres := tres_exists
	if tres_exists and json_exists:
		var json_time := FileAccess.get_modified_time(WORDS_PATH)
		var tres_time := FileAccess.get_modified_time(WORD_BANK_TRES)
		if json_time > tres_time:
			prefer_tres = false
			push_warning(
				"WordEngine: words.json is newer than word_bank.tres. " +
				"Loading JSON directly. Run `godot --headless --script tools/import_words.gd` " +
				"to refresh the .tres cache."
			)
	if prefer_tres and _load_from_tres():
		return
	if json_exists and _load_from_json():
		return
	push_warning("WordEngine: No word bank found, using built-in emergency fallback")
	_use_builtin_words()
	print("WordEngine: Loaded %d words from BUILTIN fallback" % word_bank.size())

func _load_from_tres() -> bool:
	_resource_bank = ResourceLoader.load(WORD_BANK_TRES)
	if not _resource_bank or not (_resource_bank.get("words") is Array):
		return false
	word_bank.clear()
	for entry in _resource_bank.get("words"):
		word_bank.append({
			"word": entry.get("word"),
			"level": entry.get("level"),
			"area": entry.get("area"),
			"image": entry.get("image"),
			"phonics": Array(entry.get("phonics")) if entry.get("phonics") else [],
		})
	print("WordEngine: Loaded %d words from word_bank.tres" % word_bank.size())
	return true

func _load_from_json() -> bool:
	var file := FileAccess.open(WORDS_PATH, FileAccess.READ)
	if not file:
		return false
	var json := JSON.new()
	var err := json.parse(file.get_as_text())
	file.close()
	if err != OK:
		push_warning("WordEngine: Failed to parse words.json: " + json.get_error_message())
		return false
	var raw_words: Array = json.data.get("words", [])
	if raw_words.is_empty():
		return false
	word_bank.clear()
	for entry in raw_words:
		word_bank.append(entry)
	print("WordEngine: Loaded %d words from words.json" % word_bank.size())
	return true

func _use_builtin_words() -> void:
	# EMERGENCY FALLBACK ONLY — runs when both data/words.json AND
	# data/words/word_bank.tres are missing or unreadable.
	#
	# DO NOT ADD WORDS HERE. The single source of truth is data/words.json.
	# After editing words.json, run:
	#   godot --headless --script tools/import_words.gd
	# to refresh word_bank.tres.
	word_bank = [
		{"word": "cat", "level": 1, "area": "meadow", "image": "cat", "phonics": ["c","a","t"]},
		{"word": "dog", "level": 1, "area": "meadow", "image": "dog", "phonics": ["d","o","g"]},
		{"word": "sun", "level": 1, "area": "meadow", "image": "sun", "phonics": ["s","u","n"]},
		{"word": "hat", "level": 1, "area": "meadow", "image": "hat", "phonics": ["h","a","t"]},
		{"word": "bed", "level": 1, "area": "meadow", "image": "bed", "phonics": ["b","e","d"]},
		{"word": "pig", "level": 1, "area": "meadow", "image": "pig", "phonics": ["p","i","g"]},
		{"word": "hut", "level": 1, "area": "meadow", "image": "hut", "phonics": ["h","u","t"]},
		{"word": "zap", "level": 1, "area": "meadow", "image": "zap", "phonics": ["z","a","p"]},
	]

func select_word_for_area(area: String) -> String:
	# Teleport (zap) is always available — no forced word needed

	# Force HUT if player has 3+ companions but no hut yet
	if "hut" not in GameManager.words_summoned:
		var pet_words := ["dog", "cat", "frog", "pig", "bug", "fish", "bird", "hen", "bat", "rat", "fox", "pup"]
		var companion_count := 0
		for w in GameManager.words_summoned:
			if w in pet_words:
				companion_count += 1
		if companion_count >= 3:
			current_target_word = "HUT"
			current_hint_image = "hut"
			collected_letters.clear()
			target_word_changed.emit(current_target_word, current_hint_image)
			return current_target_word

	# Fixed starter sequence: DOG > SUN > TREE > HAMMER > HOUSE > RAINBOW
	if not _starter_complete and _starter_index < _starter_sequence.size():
		var starter_word: String = _starter_sequence[_starter_index]
		_starter_index += 1
		if _starter_index >= _starter_sequence.size():
			_starter_complete = true
		# Find matching entry in word bank for hint image
		var hint := starter_word
		for entry in word_bank:
			if entry.get("word", "") == starter_word:
				hint = entry.get("image", starter_word)
				break
		current_target_word = starter_word.to_upper()
		current_hint_image = hint
		collected_letters.clear()
		target_word_changed.emit(current_target_word, current_hint_image)
		return current_target_word

	# Priority: Francis needs a HAMMER to dig + build. If he hasn't earned one yet,
	# push HAMMER ahead of everything until he spells it (then it's his forever).
	if "hammer" not in GameManager.items_owned:
		current_target_word = "HAMMER"
		current_hint_image = "hammer"
		collected_letters.clear()
		target_word_changed.emit(current_target_word, current_hint_image)
		return current_target_word

	# After starter sequence, random selection by area + difficulty.
	# HARD RULE: a spelled word is NEVER offered again until EVERY word has been spelled.
	# Tracked via GameManager.words_completed — which records ALL spelled words (including
	# temporary-effect words like BIG) and persists across restarts. No "repeatable" exception.
	# Word difficulty scales with game level AND progression
	var game_level: int = GameManager.current_level  # 1 = surface, 2 = underground, etc.
	var max_difficulty: int = maxi(current_difficulty, game_level)

	# Priority: current game level words first, then allow all up to max
	var candidates := word_bank.filter(func(w: Dictionary) -> bool:
		var wl: int = w.get("level", 1)
		var word: String = w.get("word", "")
		var not_done := word not in GameManager.words_completed
		# Offer every word UP TO the player's current difficulty (so reaching level 2
		# surfaces level-2 words), in this area, not already learned. never_done priority
		# below still puts brand-new words first.
		return wl <= max_difficulty and w.get("area", "") == area.to_lower() and not_done
	)
	if candidates.is_empty():
		# Relax: allow current level words from any area
		candidates = word_bank.filter(func(w: Dictionary) -> bool:
			var wl: int = w.get("level", 1)
			var word: String = w.get("word", "")
			var not_done := word not in GameManager.words_completed
			return wl == game_level and not_done and wl <= max_difficulty
		)
	if candidates.is_empty():
		# Relax further: allow any level up to max
		candidates = word_bank.filter(func(w: Dictionary) -> bool:
			var wl: int = w.get("level", 1)
			var word: String = w.get("word", "")
			var not_done := word not in GameManager.words_completed
			return wl <= max_difficulty and not_done
		)
	if candidates.is_empty():
		# All words done at this difficulty, allow repeats
		candidates = word_bank.filter(func(w: Dictionary) -> bool:
			return w.get("level", 1) <= max_difficulty
		)
	if candidates.is_empty():
		return "cat"

	# Priority 1: ALWAYS prefer words never spelled yet (new words = learning!)
	var never_done := candidates.filter(func(w: Dictionary) -> bool:
		return w.get("word", "") not in GameManager.words_completed
	)
	if not never_done.is_empty():
		candidates = never_done

	# Priority 2: Filter out recently used words
	var fresh := candidates.filter(func(w: Dictionary) -> bool:
		return w.get("word", "") not in _recent_words
	)
	if not fresh.is_empty():
		candidates = fresh
	elif _recent_words.size() > 0:
		# At minimum avoid the very last word
		var last_word: String = _recent_words[-1]
		var not_last := candidates.filter(func(w: Dictionary) -> bool:
			return w.get("word", "") != last_word
		)
		if not not_last.is_empty():
			candidates = not_last

	var entry: Dictionary = candidates[randi() % candidates.size()]
	current_target_word = entry.get("word", "cat").to_upper()
	current_hint_image = entry.get("image", "")
	collected_letters.clear()
	target_word_changed.emit(current_target_word, current_hint_image)
	return current_target_word

func try_collect_letter(letter: String) -> bool:
	letter = letter.to_upper()
	if current_target_word.is_empty():
		return false
	var next_index := collected_letters.size()
	if next_index >= current_target_word.length():
		return false
	var expected := current_target_word[next_index]
	if letter == expected:
		collected_letters.append(letter)
		letter_collected.emit(letter, next_index)
		if collected_letters.size() == current_target_word.length():
			_on_word_complete()
		return true
	else:
		wrong_letter_rejected.emit(letter)
		return false

func _on_word_complete() -> void:
	var word := current_target_word.to_lower()
	# Track recent words to avoid repetition
	_recent_words.append(word)
	if _recent_words.size() > RECENT_WORD_MEMORY:
		_recent_words.pop_front()
	word_spelled_correctly.emit(word)
	GameManager.complete_word(word)
	# Sync starter progress to GameManager for persistence
	GameManager.starter_index = _starter_index
	GameManager.starter_complete = _starter_complete
	_track_attempt(word, true)
	_check_difficulty_progression()

func _track_attempt(word: String, correct: bool) -> void:
	if word not in _word_attempts:
		_word_attempts[word] = {"correct": 0, "hints_used": 0}
	if correct:
		_word_attempts[word]["correct"] += 1

func _check_difficulty_progression() -> void:
	var total := GameManager.get_total_words_completed()
	if total >= 60:
		current_difficulty = 5
	elif total >= 40:
		current_difficulty = 4
	elif total >= 25:
		current_difficulty = 3
	elif total >= 10:
		current_difficulty = 2
	else:
		current_difficulty = 1

func get_current_difficulty() -> int:
	return current_difficulty

func get_letters_needed() -> Array[String]:
	var needed: Array[String] = []
	for i in range(current_target_word.length()):
		needed.append(current_target_word[i])
	return needed

func get_next_needed_letter() -> String:
	var idx := collected_letters.size()
	if idx < current_target_word.length():
		return current_target_word[idx]
	return ""

func get_progress_for_current_word() -> float:
	if current_target_word.is_empty():
		return 0.0
	return float(collected_letters.size()) / float(current_target_word.length())

func is_word_complete() -> bool:
	return collected_letters.size() == current_target_word.length() and not current_target_word.is_empty()

func _on_progress_reset() -> void:
	_starter_index = 0
	_starter_complete = false
	current_target_word = ""
	current_hint_image = ""
	collected_letters.clear()
	current_difficulty = 1
	_word_attempts.clear()
	_recent_words.clear()
